@php($title = "Nerve Conduction | Dr. Vishal Chafale Neurologist Navi Mumbai")
@section('meta_desc')Get expert epilepsy treatment from Dr. Vishal Chafale, leading neurologist in Navi Mumbai. Comprehensive care for better health ..@endsection

@extends('layouts.default')

@section('content')

<section id="ft-breadcrumb" class="ft-breadcrumb-section position-relative" data-background="assets/img/bg/bread-bg.jpg" style="background-image: url(&quot;assets/img/bg/bread-bg.jpg&quot;);">
	<span class="background_overlay"></span>
	<span class="design-shape position-absolute"><img src="assets/img/shape/tmd-sh.png" alt=""></span>
	<div class="container">
		<div class="ft-breadcrumb-content headline text-center position-relative">
			<h2>Nerve Conduction Studies</h2>
			<div class="ft-breadcrumb-list ul-li">
				<ul>
					<li><a href="#">Blog</a></li>
					<li>Nerve Conduction Studies</li>
				</ul>
			</div>
		</div>
	</div>
</section>

<!--blog-->

<section>
   <div class="container">
      <div class="row">
         <div class="blog--contents">
            <img src="{{ asset('/resources/assets/images/blogs/nerve-conduction-studies.png'); }}" alt="">
         </div>
         
         <div class="blog-main-content">
             <h2>NERVE CONDUCTION STUDIES</h2>
             
             <p>A nerve conduction study (NCS) is an electrodiagnostic test used to evaluate the electrical conduction, and thus the
function of the motor and sensory nerves of the body.</p>
             
             <!---->
             <h2>Uses </h2>

<div class="list-blog  ul-li-block">
   
       <ul class="list--items">
        <i class="fa-solid fa-angle-right"></i>
        <li>Uses of sensory NCS include evaluating parasthesias (numbness, tingling burning sensations) in a limb or a part
of the limb (eg. Carpal tunnel syndrome, Guyon's canal syndrome, peroneal neuropathy), in two or more limbs or parts
of the limbs (eg. Guillain -Barré syndrome, diabetic neuropathy) Uses of motor NCS include evaluating weakness in
muscle/s of limb/s (eg. nerve root compression due to herniated disc, motor neuron disease, muscular dystrophy,
poliomyelitis).</li>
   
    
        </ul>
        
        
</div>

             <!---->


             <!---->
             <div class="list-blog-set  ul-li-block">
        
        <h4>INDICATIONS</h4>

        <p>NCS is indicated when there is:</p>
   
       <ul class="list--items">
      
         <i class="fa-solid fa-angle-right"></i>
         <li>Weakness in the limb/s</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>parasthesias in the limb/s</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>Painin the limb/s</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>Suspected spinal nerve compression</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>Suspected neurologic injury or disorder affecting peripheral nerves</li>
         
    
       
        </ul>

        
        
</div>
             <!---->
             
             
             <div class="list-blog  ul-li-block">
   
     
        <!---->
        
        <ul class="list--items">
        <i class="fa-solid fa-angle-right"></i>
        <li> <span class="bold-blog"> Electromyography (EMG) </span>is an electrodiagnostic technique used for recording the electrical activity produced by skeletal
muscles. An electromyograph is used to detect the electrical potentials generated by muscle cells when they are
neurologically or electrically activated. These signals are then analyzed to evaluate normal or abnormal activation level
and recruitment of muscle fibers in various disorders of muscles and nerves of central nervous system as well as
peripheral nervous system.
 </li>


      
        </ul>
        
        
</div>


<!---->

<div class="list-blog-set  ul-li-block">
        
        <h4>Uses</h4>


   
       <ul class="list--items">
      
         <i class="fa-solid fa-angle-right"></i>
         <li>To identify neuromuscular disorders</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To diagnose peripheral nerve compression or injury (eg. Carpal tunnel syndrome, Cubital tunnel syndrome)</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To identify nerve root compression or injury (eg. due to herniated intervertebral disc, sciatica)</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To check for causes of muscle weakness and wasting and help differentiate between neuropathy and myopathy</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To diagnose muscle disorders such as muscular dystrophy</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To evaluate motor problems such as involuntary muscle nvitching (eg. Motor neuron disease)</li>
         <i class="fa-solid fa-angle-right"></i>
         <li>To diagnose disorders those affect the motor neurons in the spinal cord, such as amyotrophic lateral sclerosis or polio</li>
        
       
    
       
        </ul>

        
        
</div>


            
         </div>
         
         
         
         
         
         
      </div>
   </div>
</section>
<!--blog end-->

@stop
